ci: cache the built shader artifact
Pretty much the same as what we just did for shader_builder.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,7 +37,7 @@ jobs:
         id: rust-cache
         with:
           save-if: ${{ inputs.save_cache && github.ref_type != 'tag' }}
-          cache-directories: .tmp/sb
+          cache-directories: .temp/sb
           key: ${{ hashFiles('shader_builder/**') }}
 
       - name: Determine build status
@@ -48,7 +48,6 @@ jobs:
           echo RCC cache hit: ${{ steps.rust-cache.outputs.cache-hit }} : ${{ steps.rust-cache.outputs.cache-hit == 'true' }}
           echo do-build decision: $do_build
           echo do-build=$do_build >> $GITHUB_OUTPUT
-          ls -lR .temp/sb || true
 
       # Build and tooling actions (gated by the status check)
       # N.B. We don't need to install the spirv-tools .deb here, as we're not actually using them in this job
@@ -73,6 +72,7 @@ jobs:
         with:
           name: shader_builder
           path: .temp/sb/*
+          if-no-files-found: error
         if: ${{ !cancelled() }}
 
   shader:
@@ -80,35 +80,58 @@ jobs:
     timeout-minutes: 30
     needs: shader_builder
     steps:
-      - name: Install spirv-tools
-        run: sudo apt update && sudo apt install spirv-tools
+      - uses: actions/checkout@v6
+      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
+        id: rust-cache
+        with:
+          save-if: ${{ github.ref_type != 'tag' }}
+          cache-directories: .temp/shader
+          key: ${{ hashFiles('lib/**') }}
+      - name: Determine build status
+        id: do-build
+        run: |
+          echo Cache hit status: Rust ${{ steps.rust-cache.outputs.cache-hit }}
+          do_build=${{ (steps.rust-cache.outputs.cache-hit != 'true') && '1' || '0' }}
+          echo do-build decision: $do_build
+          echo do-build=$do_build >> $GITHUB_OUTPUT
+          ls -lR .temp/shader || true
+
+      # Tool installation and shader build are gated by the status check
       - name: Install Rust
         uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
+        if: ${{ steps.do-build.outputs.do-build == '1' }}
         with:
           toolchain: ${{ env.BROT3_RUST_VERSION }}
           components: rust-src,rustc-dev,llvm-tools
-      - uses: actions/checkout@v6
       - name: Download shader_builder
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        if: ${{ steps.do-build.outputs.do-build == '1' }}
         with:
           name: shader_builder
           path: ${{ github.workspace }}/.temp/shader_builder
-      - name: Fix permissions
-        run: ls -lR .temp ; chmod -v +x ${{ github.workspace }}/.temp/shader_builder/*
-      # This is not currently worth cacheing. A 110M cache but no time saving overall.
-      #- uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
-      #  with:
-      #    save-if: ${{ github.ref_type != 'tag' }}
+      - name: Install spirv-tools, fix permissions
+        run: |
+          sudo apt update && sudo apt install spirv-tools
+          ls -lR .temp ; chmod -v +x ${{ github.workspace }}/.temp/shader_builder/*
+        if: ${{ steps.do-build.outputs.do-build == '1' }}
       - name: build shader
+        if: ${{ steps.do-build.outputs.do-build == '1' }}
         env:
           LD_LIBRARY_PATH: ${{ github.workspace }}/.temp/shader_builder
-        run: pwd; ls -lR .temp/shader_builder; ./.temp/shader_builder/shader_builder
-        # Continue on error as far as possible, to provide maximum useful information
-      - name: Upload SPIRV artifact
+        run: |
+          pwd; ls -lR .temp/shader_builder
+          ./.temp/shader_builder/shader_builder
+          mkdir -p .temp/shader
+          cp target/spirv-builder/spirv-unknown-vulkan1.1/release/deps/*.spv .temp/shader
+
+      # This step is unconditional so the result can be used by later jobs
+      - name: Upload artifact
         uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
         with:
           name: brot3_lib.spv
-          path: target/spirv-builder/spirv-unknown-vulkan1.1/release/deps/brot3_lib.spv
+          path: .temp/shader/
+          if-no-files-found: error
+        # Try to upload on error, to provide maximum useful information for a human diagnostic
         if: ${{ !cancelled() }}
 
   ui-hot-reload:
