chore(ci): review ci, split up jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,7 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  BROT3_RUST_VERSION: 1.89
 
 jobs:
   # Build the app on all supported platforms
@@ -23,26 +24,66 @@ jobs:
     runs-on: ${{ matrix.platform }}
     steps:
     - uses: actions/checkout@v4
+    - name: Install Rust
+      uses: dtolnay/rust-toolchain@master
+      with:
+        toolchain: ${{ env.BROT3_RUST_VERSION }}
     - name: Set minimal profile (Windows only)
       if: matrix.platform == 'windows-latest'
       run: rustup set profile minimal
-    - uses: Swatinem/rust-cache@v2
-      with:
-        key: "${{matrix.platform}}"
-    - name: install packages (ubuntu)
+    - uses:
+        Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
+      #with:
+      #  key: "${{matrix.platform}}"
+    - name: install mold (ubuntu)
       if: matrix.platform == 'ubuntu-latest'
       run: sudo apt-get update && sudo apt-get -y --no-install-recommends install mold
-    - name: Build
-      run: cargo build --locked
+    - run: cargo build --locked --release
 
   # We only need to run the checks on a single platform
-  checks:
+  clippy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: Swatinem/rust-cache@v2
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@master
         with:
-          key: ubuntu-latest
+          toolchain: ${{ env.BROT3_RUST_VERSION }}
+          components: rustfmt,clippy,rust-src
+      - name: install mold
+        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install mold
+      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
+      - run: cargo fmt --all -- --check
+      - run: cargo clippy --all-targets --locked --workspace
+
+  tests:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          toolchain: ${{ env.BROT3_RUST_VERSION }}
+      - name: install mold
+        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install mold
+      # 20/8/25 not currently worthwhile
+      #- uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
+      #  with:
+      #    cache-on-failure: true
+      - run: cargo test --locked
+
+  bench:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          toolchain: ${{ env.BROT3_RUST_VERSION }}
+      # 20/8/25 not currently worthwhile
+      #- uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
+      #  with:
+      #    cache-on-failure: true
       - name: Install cargo-binstall
         uses: cargo-bins/cargo-binstall@v1.12.6
       - name: Interrogate cargo for required tool versions
@@ -53,14 +94,10 @@ jobs:
           cat $GITHUB_OUTPUT
       - name: install IAI runner
         run: cargo binstall --no-confirm --force iai-callgrind-runner@${{ steps.cargo.outputs.iai_callgrind }}
-      - name: install deb packages
+      - name: install mold,valgrind
         run: sudo apt-get update && sudo apt-get -y --no-install-recommends install mold valgrind
-      # Checks begin here!
-      - run: cargo fmt --all -- --check
-      - run: cargo test
-      - run: cargo clippy --all-targets
       # We care that the benchmarks build and run, not about their numeric output.
-      # To keep the CI a bit leaner, do this in the dev profile.
-      - run: cargo build --all-targets
-      - run: cargo bench --profile=dev -- iai
-      - run: cargo bench --profile=dev -- fractals/iter_Original
+      # There are currently only benchmarks in brot3-engine.
+      - run: cargo bench -p brot3-engine --locked -- iai
+      - run: cargo bench -p brot3-engine --locked -- fractals/iter_Original
+        if: success() || failure()
